# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TS-Boilerplate CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      uses: bahmutov/npm-install@v1
    - name: Install client dependencies
      uses: bahmutov/npm-install@v1
      with:
        working-directory: src/client   
    - name: Get changed files
      id: get_changed_files
      uses: dorner/file-changes-action@v1.2.0
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        plaintext: true
    - name: Run ESLint
      # Get all changed files, filter to only .js, .ts, .tsx, and lint them
      run: yarn ci-lint `echo ${{ steps.get_changed_files.outputs.files }} | tr " " "\n" | grep ".js$\|.ts$\|.tsx" | tr "\n" " "`
    - name: Build Typescript
      run: yarn build
    - name: Run tests 
      run: yarn test
